from app1.views import home
from . import views
from django.urls import path
urlpatterns = [
    path('', home),
    path('final_velocity1/', views.final_velocity1,name='final_velocity1'),
    path('final_velocity2/', views.final_velocity2,name='final_velocity2'),
    path('displacement/', views.displacement, name='displacement'),
    path('energy_light/', views.energy_light, name='energy_light'),
    path('time_flight/', views.time_flight, name='time_flight'),
    path('max_height/', views.max_height, name='max_height'),
    path('horizontal_range/', views.horizontal_range, name='horizontal_range'),
    path('capacitance/', views.parallel_plate_capacitance, name='par_plate_capacitance'),
    path('half_life/', views.half_life, name='half_life'),
    path('energy_kinetic/', views.kinetic_energy, name='kinetic_energy'),
    path('capacitor_pot_energy/',views.capacitor_pot_energy,name='capacitor_pot_energy'),
    path('grav_pot_energy/', views.grav_pot_energy, name='gravitational_pot_energy'),
    path('ohm_law/',views.ohm_law,name='ohm_law'),
    path('snell_law/', views.snell_law, name='snell_law'),
    path('emf_conductor/', views.emf_wire,name='emf_conductor'),
    path('coulomb_law/', views.coulomb_law, name='coulomb_law'),
    path('grav_law/', views.gravitational_law, name='grav_law'),
    path('centripetal_force/',views.centripetal_force, name='centripetal_force'),
    path('focal_length/', views.thin_lens_eq, name='focal_length'),
    path('energy_quant/',views.einstein_eq,name='einstein_eq'),
    path('resistivity/', views.resistivity,name='resistivity'),
    path('rotational_kinetic_energy/', views.rot_kinetic_energy, name='rotational_kinetic_energy'),
    path('work_energy_theorem/',views.work_energy_theorem,name='work_energy_theorem'),
    path('net_internal_energy/',views.net_internal_energy,name='net_internal_energy'),
    path('photon_momentum/',views.photon_momentum,name='photon_momentum'),
    path('impedance/', views.impedance_lcr, name='impedance_lcr'),
    path('resonant_frequency/',views.resonant_frequency,name='resonant_frequency'),
    path('newton_force/',views.newton_force,name='newton_force'),
    path('radioactivity_law/',views.radioactivity_law,name='radioactivity_law'),
    path('potential_energy_inductor/',views.pot_energy_inductor,name='potential_energy_inductor'),
    path('escape_velocity/', views.escape_velocity,name='escape_velocity'),
    path('orbital_velocity/', views.orbital_velocity, name='orbital_velocity'),
    path('critical_angle/', views.critical_angle, name='critical_angle'),
    path('hooke_law/',views.hooke_law,name='hooke_law'),
    path('potential_energy_spring/',views.pot_energy_spring,name='potential_energy_spring')
]